//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S2G6_PVFAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salesperson
    {
        public string salespersonID { get; set; }
        public string salespersonName { get; set; }
        public string salespersonTelephone { get; set; }
        public string salespersonFax { get; set; }
        public string territoryID { get; set; }
    
        public virtual Territory Territory { get; set; }
    }
}
