//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S2G6_PVFAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supply
    {
        public string supplyUnitPrice { get; set; }
        public string supplyID { get; set; }
        public string vendorID { get; set; }
        public string materialID { get; set; }
    
        public virtual Raw_Material Raw_Material { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
