//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S2G6_PVFAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Works_In
    {
        public string worksinID { get; set; }
        public string workscenterID { get; set; }
        public string employeeID { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Work_Center Work_Center { get; set; }
    }
}
